object FmrCalculoSalario: TFmrCalculoSalario
  Left = 0
  Top = 0
  Caption = 'FmrCalculoSalario'
  ClientHeight = 458
  ClientWidth = 893
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -12
  Font.Name = 'Segoe UI'
  Font.Style = []
  TextHeight = 15
  object Panel1: TPanel
    Left = 0
    Top = 0
    Width = 889
    Height = 74
    TabOrder = 0
    object Lblhora: TLabel
      Left = 33
      Top = 32
      Width = 57
      Height = 23
      Caption = '$ hora'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -20
      Font.Name = 'SansSerif'
      Font.Style = []
      ParentFont = False
    end
    object LblSalario: TLabel
      Left = 392
      Top = 32
      Width = 67
      Height = 23
      Caption = 'Sal'#225'rio:'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -20
      Font.Name = 'SansSerif'
      Font.Style = []
      ParentFont = False
    end
    object LblMediaMes: TLabel
      Left = 592
      Top = 32
      Width = 188
      Height = 23
      Caption = 'M'#233'dia de horas M'#234's:'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -20
      Font.Name = 'SansSerif'
      Font.Style = []
      ParentFont = False
    end
    object Edthora: TEdit
      Left = 96
      Top = 29
      Width = 162
      Height = 31
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -20
      Font.Name = 'SansSerif'
      Font.Style = []
      ParentFont = False
      TabOrder = 0
    end
    object BtnCalcular: TButton
      Left = 264
      Top = 29
      Width = 113
      Height = 32
      Caption = 'Calcular'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -20
      Font.Name = 'SansSerif'
      Font.Style = []
      ParentFont = False
      TabOrder = 1
    end
  end
  object Pnl2: TPanel
    Left = 0
    Top = 80
    Width = 889
    Height = 121
    TabOrder = 1
    object Lbl2: TLabel
      Left = 120
      Top = 16
      Width = 15
      Height = 31
      Caption = '2'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -27
      Font.Name = 'SansSerif'
      Font.Style = [fsBold]
      ParentFont = False
    end
    object Lbl3: TLabel
      Left = 207
      Top = 16
      Width = 15
      Height = 31
      Caption = '3'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -27
      Font.Name = 'SansSerif'
      Font.Style = [fsBold]
      ParentFont = False
    end
    object Lbl4: TLabel
      Left = 294
      Top = 16
      Width = 15
      Height = 31
      Caption = '4'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -27
      Font.Name = 'SansSerif'
      Font.Style = [fsBold]
      ParentFont = False
    end
    object Lbl5: TLabel
      Left = 392
      Top = 16
      Width = 15
      Height = 31
      Caption = '5'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -27
      Font.Name = 'SansSerif'
      Font.Style = [fsBold]
      ParentFont = False
    end
    object Lbl6: TLabel
      Left = 476
      Top = 16
      Width = 15
      Height = 31
      Caption = '6'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -27
      Font.Name = 'SansSerif'
      Font.Style = [fsBold]
      ParentFont = False
    end
    object Lbl7: TLabel
      Left = 563
      Top = 16
      Width = 15
      Height = 31
      Caption = '7'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -27
      Font.Name = 'SansSerif'
      Font.Style = [fsBold]
      ParentFont = False
    end
    object Lbl8: TLabel
      Left = 650
      Top = 16
      Width = 15
      Height = 31
      Caption = '8'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -27
      Font.Name = 'SansSerif'
      Font.Style = [fsBold]
      ParentFont = False
    end
    object Lbl9: TLabel
      Left = 737
      Top = 16
      Width = 15
      Height = 31
      Caption = '9'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -27
      Font.Name = 'SansSerif'
      Font.Style = [fsBold]
      ParentFont = False
    end
    object Lbl10: TLabel
      Left = 817
      Top = 16
      Width = 30
      Height = 31
      Caption = '10'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -27
      Font.Name = 'SansSerif'
      Font.Style = [fsBold]
      ParentFont = False
    end
    object Lbl1: TLabel
      Left = 33
      Top = 16
      Width = 15
      Height = 31
      Caption = '1'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -27
      Font.Name = 'SansSerif'
      Font.Style = [fsBold]
      ParentFont = False
    end
    object Edt1: TEdit
      Left = 17
      Top = 53
      Width = 50
      Height = 40
      Font.Charset = SYMBOL_CHARSET
      Font.Color = clWindowText
      Font.Height = -19
      Font.Name = 'SansSerif'
      Font.Style = []
      ParentFont = False
      TabOrder = 0
    end
    object Edt2: TEdit
      Left = 105
      Top = 53
      Width = 50
      Height = 40
      Font.Charset = SYMBOL_CHARSET
      Font.Color = clWindowText
      Font.Height = -19
      Font.Name = 'SansSerif'
      Font.Style = []
      ParentFont = False
      TabOrder = 1
    end
    object Edt3: TEdit
      Left = 193
      Top = 53
      Width = 50
      Height = 40
      Font.Charset = SYMBOL_CHARSET
      Font.Color = clWindowText
      Font.Height = -19
      Font.Name = 'SansSerif'
      Font.Style = []
      ParentFont = False
      TabOrder = 2
    end
    object Edt4: TEdit
      Left = 281
      Top = 53
      Width = 50
      Height = 40
      Font.Charset = SYMBOL_CHARSET
      Font.Color = clWindowText
      Font.Height = -19
      Font.Name = 'SansSerif'
      Font.Style = []
      ParentFont = False
      TabOrder = 3
    end
    object Edt5: TEdit
      Left = 377
      Top = 53
      Width = 50
      Height = 40
      Font.Charset = SYMBOL_CHARSET
      Font.Color = clWindowText
      Font.Height = -19
      Font.Name = 'SansSerif'
      Font.Style = []
      ParentFont = False
      TabOrder = 4
    end
    object Edt6: TEdit
      Left = 457
      Top = 53
      Width = 50
      Height = 40
      Font.Charset = SYMBOL_CHARSET
      Font.Color = clWindowText
      Font.Height = -19
      Font.Name = 'SansSerif'
      Font.Style = []
      ParentFont = False
      TabOrder = 5
    end
    object Edt7: TEdit
      Left = 545
      Top = 53
      Width = 50
      Height = 40
      Font.Charset = SYMBOL_CHARSET
      Font.Color = clWindowText
      Font.Height = -19
      Font.Name = 'SansSerif'
      Font.Style = []
      ParentFont = False
      TabOrder = 6
    end
    object Edt8: TEdit
      Left = 633
      Top = 53
      Width = 50
      Height = 40
      Font.Charset = SYMBOL_CHARSET
      Font.Color = clWindowText
      Font.Height = -19
      Font.Name = 'SansSerif'
      Font.Style = []
      ParentFont = False
      TabOrder = 7
    end
    object Edt9: TEdit
      Left = 721
      Top = 53
      Width = 50
      Height = 40
      Font.Charset = SYMBOL_CHARSET
      Font.Color = clWindowText
      Font.Height = -19
      Font.Name = 'SansSerif'
      Font.Style = []
      ParentFont = False
      TabOrder = 8
    end
    object Edt10: TEdit
      Left = 809
      Top = 53
      Width = 50
      Height = 40
      Font.Charset = SYMBOL_CHARSET
      Font.Color = clWindowText
      Font.Height = -19
      Font.Name = 'SansSerif'
      Font.Style = []
      ParentFont = False
      TabOrder = 9
    end
  end
  object Pnl3: TPanel
    Left = 0
    Top = 207
    Width = 889
    Height = 122
    TabOrder = 2
    object Lbl11: TLabel
      Left = 18
      Top = 18
      Width = 30
      Height = 31
      Caption = '11'
      Font.Charset = SYMBOL_CHARSET
      Font.Color = clWindowText
      Font.Height = -27
      Font.Name = 'SansSerif'
      Font.Style = [fsBold]
      ParentFont = False
    end
    object Lbl12: TLabel
      Left = 105
      Top = 16
      Width = 30
      Height = 31
      Caption = '12'
      Font.Charset = SYMBOL_CHARSET
      Font.Color = clWindowText
      Font.Height = -27
      Font.Name = 'SansSerif'
      Font.Style = [fsBold]
      ParentFont = False
    end
    object Lbl13: TLabel
      Left = 193
      Top = 16
      Width = 30
      Height = 31
      Caption = '13'
      Font.Charset = SYMBOL_CHARSET
      Font.Color = clWindowText
      Font.Height = -27
      Font.Name = 'SansSerif'
      Font.Style = [fsBold]
      ParentFont = False
    end
    object Lbl14: TLabel
      Left = 284
      Top = 16
      Width = 30
      Height = 31
      Caption = '14'
      Font.Charset = SYMBOL_CHARSET
      Font.Color = clWindowText
      Font.Height = -27
      Font.Name = 'SansSerif'
      Font.Style = [fsBold]
      ParentFont = False
    end
    object Lbl15: TLabel
      Left = 377
      Top = 16
      Width = 30
      Height = 31
      Caption = '15'
      Font.Charset = SYMBOL_CHARSET
      Font.Color = clWindowText
      Font.Height = -27
      Font.Name = 'SansSerif'
      Font.Style = [fsBold]
      ParentFont = False
    end
    object Lbl16: TLabel
      Left = 461
      Top = 16
      Width = 30
      Height = 31
      Caption = '16'
      Font.Charset = SYMBOL_CHARSET
      Font.Color = clWindowText
      Font.Height = -27
      Font.Name = 'SansSerif'
      Font.Style = [fsBold]
      ParentFont = False
    end
    object Lbl17: TLabel
      Left = 550
      Top = 16
      Width = 30
      Height = 31
      Caption = '17'
      Font.Charset = SYMBOL_CHARSET
      Font.Color = clWindowText
      Font.Height = -27
      Font.Name = 'SansSerif'
      Font.Style = [fsBold]
      ParentFont = False
    end
    object Lbl18: TLabel
      Left = 639
      Top = 16
      Width = 30
      Height = 31
      Caption = '18'
      Font.Charset = SYMBOL_CHARSET
      Font.Color = clWindowText
      Font.Height = -27
      Font.Name = 'SansSerif'
      Font.Style = [fsBold]
      ParentFont = False
    end
    object Lbl19: TLabel
      Left = 728
      Top = 16
      Width = 30
      Height = 31
      Caption = '19'
      Font.Charset = SYMBOL_CHARSET
      Font.Color = clWindowText
      Font.Height = -27
      Font.Name = 'SansSerif'
      Font.Style = [fsBold]
      ParentFont = False
    end
    object Lbl20: TLabel
      Left = 817
      Top = 16
      Width = 30
      Height = 31
      Caption = '20'
      Font.Charset = SYMBOL_CHARSET
      Font.Color = clWindowText
      Font.Height = -27
      Font.Name = 'SansSerif'
      Font.Style = [fsBold]
      ParentFont = False
    end
    object Edit1: TEdit
      Left = 17
      Top = 55
      Width = 50
      Height = 40
      Font.Charset = SYMBOL_CHARSET
      Font.Color = clWindowText
      Font.Height = -19
      Font.Name = 'SansSerif'
      Font.Style = []
      ParentFont = False
      TabOrder = 0
    end
    object Edit2: TEdit
      Left = 105
      Top = 53
      Width = 50
      Height = 40
      Font.Charset = SYMBOL_CHARSET
      Font.Color = clWindowText
      Font.Height = -19
      Font.Name = 'SansSerif'
      Font.Style = []
      ParentFont = False
      TabOrder = 1
    end
    object Edit3: TEdit
      Left = 193
      Top = 53
      Width = 50
      Height = 40
      Font.Charset = SYMBOL_CHARSET
      Font.Color = clWindowText
      Font.Height = -19
      Font.Name = 'SansSerif'
      Font.Style = []
      ParentFont = False
      TabOrder = 2
    end
    object Edit4: TEdit
      Left = 281
      Top = 53
      Width = 50
      Height = 40
      Font.Charset = SYMBOL_CHARSET
      Font.Color = clWindowText
      Font.Height = -19
      Font.Name = 'SansSerif'
      Font.Style = []
      ParentFont = False
      TabOrder = 3
    end
    object Edit5: TEdit
      Left = 377
      Top = 53
      Width = 50
      Height = 40
      Font.Charset = SYMBOL_CHARSET
      Font.Color = clWindowText
      Font.Height = -19
      Font.Name = 'SansSerif'
      Font.Style = []
      ParentFont = False
      TabOrder = 4
    end
    object Edit6: TEdit
      Left = 457
      Top = 53
      Width = 50
      Height = 40
      Font.Charset = SYMBOL_CHARSET
      Font.Color = clWindowText
      Font.Height = -19
      Font.Name = 'SansSerif'
      Font.Style = []
      ParentFont = False
      TabOrder = 5
    end
    object Edit7: TEdit
      Left = 545
      Top = 53
      Width = 50
      Height = 40
      Font.Charset = SYMBOL_CHARSET
      Font.Color = clWindowText
      Font.Height = -19
      Font.Name = 'SansSerif'
      Font.Style = []
      ParentFont = False
      TabOrder = 6
    end
    object Edit8: TEdit
      Left = 633
      Top = 53
      Width = 50
      Height = 40
      Font.Charset = SYMBOL_CHARSET
      Font.Color = clWindowText
      Font.Height = -19
      Font.Name = 'SansSerif'
      Font.Style = []
      ParentFont = False
      TabOrder = 7
    end
    object Edit9: TEdit
      Left = 721
      Top = 53
      Width = 50
      Height = 40
      Font.Charset = SYMBOL_CHARSET
      Font.Color = clWindowText
      Font.Height = -19
      Font.Name = 'SansSerif'
      Font.Style = []
      ParentFont = False
      TabOrder = 8
    end
    object Edit10: TEdit
      Left = 809
      Top = 53
      Width = 50
      Height = 40
      Font.Charset = SYMBOL_CHARSET
      Font.Color = clWindowText
      Font.Height = -19
      Font.Name = 'SansSerif'
      Font.Style = []
      ParentFont = False
      TabOrder = 9
    end
  end
  object Pnl4: TPanel
    Left = 0
    Top = 335
    Width = 889
    Height = 123
    TabOrder = 3
    object Label1: TLabel
      Left = 33
      Top = 16
      Width = 30
      Height = 31
      Caption = '21'
      Font.Charset = SYMBOL_CHARSET
      Font.Color = clWindowText
      Font.Height = -27
      Font.Name = 'SansSerif'
      Font.Style = [fsBold]
      ParentFont = False
    end
    object Label2: TLabel
      Left = 120
      Top = 16
      Width = 30
      Height = 31
      Caption = '22'
      Font.Charset = SYMBOL_CHARSET
      Font.Color = clWindowText
      Font.Height = -27
      Font.Name = 'SansSerif'
      Font.Style = [fsBold]
      ParentFont = False
    end
    object Label3: TLabel
      Left = 207
      Top = 16
      Width = 30
      Height = 31
      Caption = '23'
      Font.Charset = SYMBOL_CHARSET
      Font.Color = clWindowText
      Font.Height = -27
      Font.Name = 'SansSerif'
      Font.Style = [fsBold]
      ParentFont = False
    end
    object Label4: TLabel
      Left = 294
      Top = 16
      Width = 30
      Height = 31
      Caption = '24'
      Font.Charset = SYMBOL_CHARSET
      Font.Color = clWindowText
      Font.Height = -27
      Font.Name = 'SansSerif'
      Font.Style = [fsBold]
      ParentFont = False
    end
    object Label5: TLabel
      Left = 381
      Top = 16
      Width = 30
      Height = 31
      Caption = '25'
      Font.Charset = SYMBOL_CHARSET
      Font.Color = clWindowText
      Font.Height = -27
      Font.Name = 'SansSerif'
      Font.Style = [fsBold]
      ParentFont = False
    end
    object Label6: TLabel
      Left = 468
      Top = 16
      Width = 30
      Height = 31
      Caption = '26'
      Font.Charset = SYMBOL_CHARSET
      Font.Color = clWindowText
      Font.Height = -27
      Font.Name = 'SansSerif'
      Font.Style = [fsBold]
      ParentFont = False
    end
    object Label7: TLabel
      Left = 555
      Top = 16
      Width = 30
      Height = 31
      Caption = '27'
      Font.Charset = SYMBOL_CHARSET
      Font.Color = clWindowText
      Font.Height = -27
      Font.Name = 'SansSerif'
      Font.Style = [fsBold]
      ParentFont = False
    end
    object Label8: TLabel
      Left = 642
      Top = 16
      Width = 30
      Height = 31
      Caption = '28'
      Font.Charset = SYMBOL_CHARSET
      Font.Color = clWindowText
      Font.Height = -27
      Font.Name = 'SansSerif'
      Font.Style = [fsBold]
      ParentFont = False
    end
    object Label9: TLabel
      Left = 729
      Top = 16
      Width = 30
      Height = 31
      Caption = '29'
      Font.Charset = SYMBOL_CHARSET
      Font.Color = clWindowText
      Font.Height = -27
      Font.Name = 'SansSerif'
      Font.Style = [fsBold]
      ParentFont = False
    end
    object Label10: TLabel
      Left = 817
      Top = 16
      Width = 30
      Height = 31
      Caption = '30'
      Font.Charset = SYMBOL_CHARSET
      Font.Color = clWindowText
      Font.Height = -27
      Font.Name = 'SansSerif'
      Font.Style = [fsBold]
      ParentFont = False
    end
    object Edt21: TEdit
      Left = 18
      Top = 53
      Width = 50
      Height = 40
      Font.Charset = SYMBOL_CHARSET
      Font.Color = clWindowText
      Font.Height = -19
      Font.Name = 'SansSerif'
      Font.Style = []
      ParentFont = False
      TabOrder = 0
    end
    object Edt22: TEdit
      Left = 105
      Top = 53
      Width = 50
      Height = 40
      Font.Charset = SYMBOL_CHARSET
      Font.Color = clWindowText
      Font.Height = -19
      Font.Name = 'SansSerif'
      Font.Style = []
      ParentFont = False
      TabOrder = 1
    end
    object Edt23: TEdit
      Left = 193
      Top = 53
      Width = 50
      Height = 40
      Font.Charset = SYMBOL_CHARSET
      Font.Color = clWindowText
      Font.Height = -19
      Font.Name = 'SansSerif'
      Font.Style = []
      ParentFont = False
      TabOrder = 2
    end
    object Edt24: TEdit
      Left = 281
      Top = 53
      Width = 50
      Height = 40
      Font.Charset = SYMBOL_CHARSET
      Font.Color = clWindowText
      Font.Height = -19
      Font.Name = 'SansSerif'
      Font.Style = []
      ParentFont = False
      TabOrder = 3
    end
    object Edt25: TEdit
      Left = 369
      Top = 53
      Width = 50
      Height = 40
      Font.Charset = SYMBOL_CHARSET
      Font.Color = clWindowText
      Font.Height = -19
      Font.Name = 'SansSerif'
      Font.Style = []
      ParentFont = False
      TabOrder = 4
    end
    object Edt26: TEdit
      Left = 457
      Top = 53
      Width = 50
      Height = 40
      Font.Charset = SYMBOL_CHARSET
      Font.Color = clWindowText
      Font.Height = -19
      Font.Name = 'SansSerif'
      Font.Style = []
      ParentFont = False
      TabOrder = 5
    end
    object Edt27: TEdit
      Left = 545
      Top = 53
      Width = 50
      Height = 40
      Font.Charset = SYMBOL_CHARSET
      Font.Color = clWindowText
      Font.Height = -19
      Font.Name = 'SansSerif'
      Font.Style = []
      ParentFont = False
      TabOrder = 6
    end
    object Edt29: TEdit
      Left = 721
      Top = 53
      Width = 50
      Height = 40
      Font.Charset = SYMBOL_CHARSET
      Font.Color = clWindowText
      Font.Height = -19
      Font.Name = 'SansSerif'
      Font.Style = []
      ParentFont = False
      TabOrder = 7
    end
    object Edt28: TEdit
      Left = 633
      Top = 53
      Width = 50
      Height = 40
      Font.Charset = SYMBOL_CHARSET
      Font.Color = clWindowText
      Font.Height = -19
      Font.Name = 'SansSerif'
      Font.Style = []
      ParentFont = False
      TabOrder = 8
    end
    object Edt30: TEdit
      Left = 809
      Top = 53
      Width = 50
      Height = 40
      Font.Charset = SYMBOL_CHARSET
      Font.Color = clWindowText
      Font.Height = -19
      Font.Name = 'SansSerif'
      Font.Style = []
      ParentFont = False
      TabOrder = 9
    end
  end
end
